server:
  port: 8084
  servlet:
    context-path: /student-service

spring:
  application:
    name: CRM
  jpa:
    hibernate:
      ddl-auto: update
      show sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/crm_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

